export {
  createLattice3D,
  estimateDenseFieldMemoryBytes,
  latticeSampleIndex,
  latticeSamplePosition,
} from "./lattice.js";
export {
  computeMeshBounds,
  fitSdfDomain,
  transformIndexedMesh,
  validateIndexedMesh,
} from "./mesh.js";
export type {
  Bounds3,
  CpuSdfBakeResult,
  CpuSdfBakeStats,
  DenseScalarField3D,
  DenseSdfBakeOptions,
  ExtractedMesh,
  FlexiCubesExtractOptions,
  FlexiCubesExtractionResult,
  FlexiCubesExtractionStats,
  FlexiCubesPhase,
  FlexiCubesProgress,
  GpuDenseScalarField3D,
  GridSize3,
  IndexedMesh,
  Lattice3D,
  Matrix4,
  ScalarFieldSignConvention,
  SdfBakePhase,
  SdfBakeProgress,
  SdfSignPolicy,
  Vec3,
  WebGpuDenseSdfBakeOptions,
  WebGpuFlexiCubesExecutionLimits,
  WebGpuFlexiCubesExtractOptions,
  WebGpuFlexiCubesExtractionResult,
  WebGpuFlexiCubesExtractionStats,
  WebGpuSdfBakeResult,
  WebGpuResidentSdfBakeResult,
  WebGpuProxyMeshResult,
  WebGpuSdfBakeStats,
  WebGpuSdfExecutionLimits,
} from "./types.js";
